UniversityManagementSystem/UniversityManagementSystem/Controllers/AllocateController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementSystem.BLL;
using UniversityManagementSystem.Models;
using UniversityManagementSystem.Models.ViewModel;

namespace UniversityManagementSystem.Controllers
{
    public class AllocateController : Controller
    {
        DepartmentManager aDepartmentManager=new DepartmentManager();
        CourseManager aCourseManager=new CourseManager();
        DayManager aDayManager=new DayManager();
        RoomManager aRoomManager=new RoomManager();
        AllocateManager aAllocateManager=new AllocateManager();

        
        public ActionResult Create()

        {
            IEnumerable<Department> departments = aDepartmentManager.GetAllDepartment();
            ViewBag.DeptList = new SelectList(departments, "Id", "Name");

            IEnumerable<Course> courses = new List<Course>();
            ViewBag.CourseList = new SelectList(courses, "Id", "Code");

            IEnumerable<Room> rooms =aRoomManager.GetAllRooms();
            ViewBag.RoomList = new SelectList(rooms, "Id", "RoomNumber");

            IEnumerable<Day> days = aDayManager.GetAllDays();
            ViewBag.DayList = new SelectList(days, "Id", "Name");
            return View();
        }

        public JsonResult GetCourseList(int departmentId)
        {
            IEnumerable<Course> coursesList = aCourseManager.GetCourseByDeptId(departmentId);
            return Json(coursesList, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult Create(AllocateClassRoomViewModel aAllocateClassRoomViewModel)
        {
            IEnumerable<Department> departments = aDepartmentManager.GetAllDepartment();
            ViewBag.DeptList = new SelectList(departments, "Id", "Name");

            IEnumerable<Course> courses = new List<Course>();
            ViewBag.CourseList = new SelectList(courses, "Id", "Code");

            IEnumerable<Room> rooms = aRoomManager.GetAllRooms();
            ViewBag.RoomList = new SelectList(rooms, "Id", "RoomNumber");

            IEnumerable<Day> days = aDayManager.GetAllDays();
            ViewBag.DayList = new SelectList(days, "Id", "Name");

            try
            {
              string msg=  aAllocateManager.SaveAllocate(aAllocateClassRoomViewModel);

                if (msg == "Class room is Full in this Time Zone")
                {
                    ViewBag.message = msg;
                    return View();
                }

                ViewBag.message = msg;
                ModelState.Clear();
                return View(new AllocateClassRoomViewModel());
            }
            catch
            {
                return View();
            }
        }

        public ActionResult ShowRoomAllocation()
        {
            IEnumerable<Department> departments = aDepartmentManager.GetAllDepartment();
            ViewBag.DeptList = new SelectList(departments, "Id", "Name");
            return View();
        }

        public JsonResult GetRoomInfoList(int departmentId)
        {
            IEnumerable<AllocateRoomViewModel> list = aAllocateManager.GetAllocateRoomList(departmentId);
            return Json(list, JsonRequestBehavior.AllowGet);
        }


        public ActionResult UnAllocateCourses()
        {
            return View();
        }
        public ActionResult UnAllocateAllCourses()
        {
            aAllocateManager.UnAllocateAllCourses();
            return RedirectToAction("UnAllocateCourses");
        }

        public ActionResult UnAllocateRooms()
        {
            return View();
        }
        public ActionResult UnAllocateAllRooms()
        {aAllocateManager.UnAllocateAllRooms();
            return RedirectToAction("UnAllocateRooms");
        }
    }
}

UniversityManagementSystem/UniversityManagementSystem/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementSystem.BLL;
using UniversityManagementSystem.Models;

namespace UniversityManagementSystem.Controllers
{
    public class CourseController : Controller
    {
        DepartmentManager aDepartmentManager=new DepartmentManager();
        SemesterManager aSemesterManager=new SemesterManager();
        CourseManager aCourseManager=new CourseManager();

       
        // GET: /Course/Create
        public ActionResult Create()
        {
            IEnumerable<Department> departments = aDepartmentManager.GetAllDepartment();
            ViewBag.DeptList=new SelectList(departments,"Id","Name");

            IEnumerable<Semester> semesters = aSemesterManager.GetAllSemesters();
            ViewBag.SemList = new SelectList(semesters, "Id", "Name");

            return View();
        }

        //
        // POST: /Course/Create
        [HttpPost]
        public ActionResult Create(Course aCourse)
        {
            try
            {
                bool errorStatus = false;

                string codeError = aCourseManager.CheckCode(aCourse.Code);
                if (codeError != null)
                {
                    ViewBag.CodeError = codeError;
                    errorStatus = true;
                }

                string nameError = aCourseManager.CheckName(aCourse.Name);
                if (nameError != null)
                {
                    ViewBag.NameError = nameError;
                    errorStatus = true;
                }

                string creditError = aCourseManager.CheckCredit(Convert.ToDouble(aCourse.Credit));
                if (creditError != null)
                {
                    ViewBag.CreditError = creditError;
                    errorStatus = true;
                }
                IEnumerable<Department> departments = aDepartmentManager.GetAllDepartment();
                ViewBag.DeptList = new SelectList(departments, "Id", "Name");

                IEnumerable<Semester> semesters = aSemesterManager.GetAllSemesters();
                ViewBag.SemList = new SelectList(semesters, "Id", "Name");
                if (errorStatus)
                {
                    
                    return View(aCourse);
                }

                string msg = aCourseManager.Save(aCourse);
                ViewBag.Msg = msg;
                 ModelState.Clear();
                
                return View(new Course());
            }
            catch
            {
                return View();
            }
        }

        

      
    }
}

UniversityManagementSystem/UniversityManagementSystem/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementSystem.BLL;
using UniversityManagementSystem.Models;

namespace UniversityManagementSystem.Controllers
{
    public class StudentController : Controller
    {
        private DepartmentManager aDepartmentManager = new DepartmentManager();
        private StudentManager aStudentManager = new StudentManager();
        CourseManager aCourseManager=new CourseManager();
        PDFManager aPdfManager=new PDFManager();
        public ActionResult Create()
        {
            IEnumerable<Department> departments = aDepartmentManager.GetAllDepartment();
            ViewBag.DeptList = new SelectList(departments, "Id", "Name");

            ViewBag.Date = DateTime.Today;
            return View();
        }

        //
        // POST: /Student/Create
        [HttpPost]
        public ActionResult Create(StudentViewModel aStudentViewModel)
        {
            try
            {
                IEnumerable<Department> departments = aDepartmentManager.GetAllDepartment();
                ViewBag.DeptList = new SelectList(departments, "Id", "Name");

                bool errorStatus = false;
                string emailError = aStudentManager.CheckEmail(aStudentViewModel.Email);
                if (emailError != null)
                {
                    ViewBag.EmailError = emailError;
                    errorStatus = true;
                }


                if (errorStatus == true)
                {
                    return View(aStudentViewModel);
                }

                string msg = aStudentManager.Save(aStudentViewModel);
                Student aStudent = aStudentManager.GetCurrentStudent();
                ViewBag.Student = aStudent;
                ViewBag.message = msg;
                ModelState.Clear();
                return View(new StudentViewModel());
            }
            catch (DbEntityValidationException e)
            {
                return View();
            }

        }
       
      public ActionResult EnrollInCourse()
      {
        IEnumerable<Student> students = aStudentManager.GetAllStudent();
        ViewBag.studentList=new SelectList(students,"Id","RegNo");

        List<Course>courses=new List<Course>();
        ViewBag.courseList = new SelectList(courses, "Id", "Name");
        return View();
      }

      public JsonResult GetCourseList(int studentId)
      {
        IEnumerable<Course> courses = aStudentManager.GetCourseListByStudentIdForJson(studentId);
        return Json(courses, JsonRequestBehavior.AllowGet);
      }
        public JsonResult GetCourseList2(int studentId)
        {
            IEnumerable<Course> courses = aStudentManager.GetCourseList2ByStudentIdForJson(studentId);
            return Json(courses, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetStudent(int studentId)
      {
        Student aStudent = aStudentManager.GetAStudentWithDeptName(studentId);
        return Json(aStudent, JsonRequestBehavior.AllowGet);
      }

      [HttpPost]
      public ActionResult EnrollInCourse(StudentEnrollViewModel aStudentEnrollViewModel)
      {
        IEnumerable<Student> students = aStudentManager.GetAllStudent();
        ViewBag.studentList = new SelectList(students, "Id", "RegNo");

        List<Course> courses = new List<Course>();
        ViewBag.courseList = new SelectList(courses, "Id", "Name");
        string msg=aStudentManager.EnrollStudentSave(aStudentEnrollViewModel);
          ViewBag.message = msg;
        ModelState.Clear();
        return View(new StudentEnrollViewModel());
      }


      public ActionResult SaveResult()
      {
        IEnumerable<Student> students = aStudentManager.GetAllStudent();
        ViewBag.studentList = new SelectList(students, "Id", "RegNo");

        List<Course> courses = new List<Course>();
        ViewBag.courseList = new SelectList(courses, "Id", "Name");
        return View();
      }
      [HttpPost]
      public ActionResult SaveResult(StudentResultViewModel aStudentResultViewModel)
      {
        IEnumerable<Student> students = aStudentManager.GetAllStudent();
        ViewBag.studentList = new SelectList(students, "Id", "RegNo");

        List<Course> courses = new List<Course>();
        ViewBag.courseList = new SelectList(courses, "Id", "Name");

          string msg = aStudentManager.SaveResult(aStudentResultViewModel);
          ViewBag.message = msg;
            ModelState.Clear();
        return View(new StudentResultViewModel());
      }


      public ActionResult ViewStudentResult()
      {
        IEnumerable<Student> students = aStudentManager.GetAllStudent();
        ViewBag.studentList = new SelectList(students, "Id", "RegNo");


        return View();
      }

        public ActionResult MakePDF(int studentId)
        {
            byte[] aBytes= aPdfManager.MakePDF(studentId);
            return File(aBytes, "application/pdf");

        }
        public JsonResult GetResultList(int studentId)
        {
            IEnumerable<ViewResultViewModel> resultList = aStudentManager.GetResultListByStudentId(studentId);
            return Json(resultList, JsonRequestBehavior.AllowGet);
        }
    }
}

UniversityManagementSystem/UniversityManagementSystem/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementSystem.BLL;
using  UniversityManagementSystem.Models;

namespace UniversityManagementSystem.Controllers
{
    public class TeacherController : Controller
    {
        DepartmentManager aDepartmentManager=new DepartmentManager();
        TeacherManager aTeacherManager=new TeacherManager();
        //
        // GET: /Teacher/
        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /Teacher/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Teacher/Create
        public ActionResult Create()
        {
            IEnumerable<Department> departments = aDepartmentManager.GetAllDepartment();
            ViewBag.DeptList = new SelectList(departments, "Id", "Name");

            IEnumerable<TeacherDesignation> designations = aTeacherManager.GetDesignations();
            ViewBag.DesgList = new SelectList(designations, "Id", "Name");
            return View();
        }

        //
        // POST: /Teacher/Create
        [HttpPost]
        public ActionResult Create(Teacher aTeacher)
        {
            try
            {
                IEnumerable<Department> departments = aDepartmentManager.GetAllDepartment();
                ViewBag.DeptList = new SelectList(departments, "Id", "Name");

                IEnumerable<TeacherDesignation> designations = aTeacherManager.GetDesignations();
                ViewBag.DesgList = new SelectList(designations, "Id", "Name");

                bool errorStatus = false;
                string creditError = aTeacherManager.CheckCredit(Convert.ToDouble(aTeacher.CreditToBeTaken));

                if (creditError != null)
                {
                    ViewBag.CreditError = creditError;
                    errorStatus = true;
                }
                string emailError = aTeacherManager.CheckEmail(aTeacher.Email);
                if (emailError != null)
                {
                    ViewBag.EmailError = emailError;
                    errorStatus = true;
                }
                if (errorStatus)
                {
                    return View(aTeacher);
                }

                string msg = aTeacherManager.Save(aTeacher);
                ViewBag.CreditError = null;
                ViewBag.Msg = msg;
                ModelState.Clear();

                return View(new Teacher());
            }
            catch
            {
                return View();
            }
        }

        

        
    }
}

UniversityManagementSystem/UniversityManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title PUBG UNIVERSITY</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("University Management System", "Index", "Home", null, new {@class = "navbar-brand"})
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <div class="dropdown">
                        <button class="dropbtn">Department</button>
                        <div class="dropdown-content">
                            @Html.ActionLink("Add Department", "Add", "Department")
                            @Html.ActionLink("View All Department", "Index", "Department")
                        </div>
                    </div>
                </li>

                <li>
                    <div class="dropdown">
                        <button class="dropbtn">Course</button>
                        <div class="dropdown-content">
                            @Html.ActionLink("Add Course", "Create", "Course")
                            @Html.ActionLink("Assign Course To Teacher", "Create", "CourseOfTeacher")
                            @Html.ActionLink("Enroll Student To Courses", "EnrollInCourse", "Student")
                        </div>
                    </div>
                </li>
                <li>
                    <div class="dropdown">
                        <button class="dropbtn">Teacher</button>
                        <div class="dropdown-content">
                            @Html.ActionLink("Add Teacher", "Create", "Teacher")
                            @Html.ActionLink("Assing Course To Teacher", "Create", "CourseOfTeacher")
                            @Html.ActionLink("See All Assigned List", "AssignedCourseListShow", "CourseOfTeacher")
                        </div>
                    </div>
                </li>


                <li>
                    <div class="dropdown">
                        <button class="dropbtn">Student</button>
                        <div class="dropdown-content">
                            @Html.ActionLink("Add Student", "Create", "Student")
                            @Html.ActionLink("Enroll Student To Courses", "EnrollInCourse", "Student")
                            @Html.ActionLink("Save Student's Result", "SaveResult", "Student")
                            @Html.ActionLink("See A Student Result", "ViewStudentResult", "Student")
                        </div>
                    </div>
                </li>
                <li>
                    <div class="dropdown">
                        <button class="dropbtn">Allocate</button>
                        <div class="dropdown-content">
                            @Html.ActionLink("Allocate Room", "Create", "Allocate")
                            @Html.ActionLink("Un-Allocate all Rooms", "UnAllocateRooms", "Allocate")
                            @Html.ActionLink("Un-Allocate all courses", "UnAllocateCourses", "Allocate")
                            @Html.ActionLink("See Allocated Rooms", "ShowRoomAllocation", "Allocate")
                        </div>
                    </div>
                </li>

            </ul>
          
        </div>
    </div>
</div>
   
    <div >@*class="container body-content"*@
        @RenderBody()
        
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - PUBG UNIVERSITY</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>